CREATE OR REPLACE FUNCTION zerobyte.ARRAY_INT64_TO_ZEROBYTE(a ARRAY< INT64 >)
AS (
  ARRAY(
    SELECT AS STRUCT
      zerobyte.INT64_TO_ZEROBYTE(i) AS _
    FROM
      UNNEST(a) AS i WITH OFFSET AS o
    ORDER BY o)
);
