CREATE OR REPLACE FUNCTION
  zerobyte.ARRAY_BOOL_TO_ZEROBYTE(a ARRAY<BOOL>)AS(ARRAY(
    SELECT
      AS STRUCT zerobyte.BOOL_TO_ZEROBYTE(b)_
    FROM
      UNNEST(a)b
    WITH
    OFFSET
      AS o
    ORDER BY
      o))
