CREATE OR REPLACE FUNCTION zerobyte.ARRAY_GEOGRAPHY_TO_ZEROBYTE(a ARRAY< GEOGRAPHY >)
AS (
  ARRAY(
    SELECT AS STRUCT
      zerobyte.GEOGRAPHY_TO_ZEROBYTE(g) AS _
    FROM
      UNNEST(a) AS g WITH OFFSET AS o
    ORDER BY o)
);
