CREATE OR REPLACE FUNCTION
  zerobyte.ARRAY_TIMESTAMP_TO_ZEROBYTE(a ARRAY<TIMESTAMP>)AS(ARRAY(
    SELECT
      AS STRUCT zerobyte.TIMESTAMP_TO_ZEROBYTE(t)_
    FROM
      UNNEST(a)t
    WITH
    OFFSET
      AS o
    ORDER BY
      o))
