CREATE OR REPLACE FUNCTION zerobyte.ARRAY_TIME_TO_ZEROBYTE(a ARRAY< TIME >)
AS (
  ARRAY(
    SELECT AS STRUCT
      zerobyte.TIME_TO_ZEROBYTE(t) AS _
    FROM
      UNNEST(a) AS t WITH OFFSET AS o
    ORDER BY o)
);
