CREATE OR REPLACE FUNCTION zerobyte.ARRAY_DATE_TO_ZEROBYTE(a ARRAY< DATE >)
AS (
  ARRAY(
    SELECT AS STRUCT
      zerobyte.DATE_TO_ZEROBYTE(d) AS _
    FROM
      UNNEST(a) AS d WITH OFFSET AS o
    ORDER BY o)
);
