CREATE OR REPLACE FUNCTION
  zerobyte.ARRAY_DATETIME_TO_ZEROBYTE(a ARRAY<DATETIME>)AS(ARRAY(
    SELECT
      AS STRUCT zerobyte.DATETIME_TO_ZEROBYTE(d)_
    FROM
      UNNEST(a)d
    WITH
    OFFSET
      AS o
    ORDER BY
      o))
