CREATE OR REPLACE FUNCTION zerobyte.BYTES_TO_ZEROBYTE(b BYTES)
AS (
  `IF`(b IS NULL, NULL, ARRAY(
      SELECT AS STRUCT
        zerobyte._NOT_NULL_INT64_TO_ZEROBYTE(i) AS _
      FROM
        UNNEST(TO_CODE_POINTS(b)) AS i WITH OFFSET AS o
      ORDER BY o))
);
