CREATE OR REPLACE FUNCTION
  zerobyte.INT64_TO_ZEROBYTE(i INT64)AS(ARRAY(
    SELECT
      AS STRUCT zerobyte.BOOL_TO_ZEROBYTE(i&1<<u=0)_
    FROM
      UNNEST(GENERATE_ARRAY(0, 63))u
    ORDER BY
      u));