CREATE OR REPLACE FUNCTION zerobyte.ZEROBYTE_TO_ARRAY_STRING(a ARRAY< STRUCT< _ ARRAY< STRUCT< _ ARRAY<
STRUCT< STRUCT< INT64 > > > > > > >)
AS (
  ARRAY(
    SELECT
      zerobyte.ZEROBYTE_TO_STRING(_)
    FROM
      UNNEST(a) WITH OFFSET AS o
    ORDER BY o)
);
