CREATE OR REPLACE FUNCTION
  zerobyte.ZEROBYTE_TO_ARRAY_BYTES(a ARRAY<STRUCT<_ ARRAY<STRUCT<_ ARRAY<STRUCT<STRUCT<INT64>>>>>>>)AS(ARRAY(
    SELECT
      zerobyte.ZEROBYTE_TO_BYTES(_)
    FROM
      UNNEST(a)
    WITH
    OFFSET
      AS o
    ORDER BY
      o))
