CREATE OR REPLACE FUNCTION
  zerobyte.ZEROBYTE_TO_BOOL(s STRUCT<_ STRUCT<_ INT64>>)AS(CASE
      WHEN s IS NULL THEN NULL
      WHEN s._ IS NULL THEN TRUE
      WHEN s._._ IS NULL THEN FALSE
    ELSE
    ERROR('Unsupported value')
  END
    )