CREATE OR REPLACE FUNCTION
  zerobyte.ZEROBYTE_TO_BYTES(a ARRAY<STRUCT<_ ARRAY<STRUCT<STRUCT<INT64>>>>>)AS(CODE_POINTS_TO_BYTES(ARRAY(
      SELECT
        zerobyte.ZEROBYTE_TO_INT64(_)
      FROM
        UNNEST(a)
      WITH
      OFFSET
        AS o)))