config {
  type: "operations",
  schema: "holidays_in_japan__us",
  tags: ["us"],
  hasOutput: true,
}

CREATE OR REPLACE FUNCTION ${self()}(d DATE)
  AS (
    d < "2000-01-01" AND EXTRACT(DAYOFYEAR FROM d) = 15
    OR "2000-01-01" <= d AND EXTRACT(MONTH FROM d) = 1 AND EXTRACT(DAYOFWEEK FROM d) = 2 AND EXTRACT(DAY FROM d) BETWEEN 8 AND 14
  )
  OPTIONS (
    description = "成人の日 1月の第2月曜日 おとなになったことを自覚し、みずから生き抜こうとする青年を祝いはげます。"
  )
