-- 体育の日	十月の第二月曜日
config {
  type: "operations",
  hasOutput: true,
  schema: "holidays_in_japan__asia_northeast1"
}
CREATE OR REPLACE FUNCTION ${self()}(d DATE)
AS (
  d BETWEEN "1966-01-01" AND "1999-12-31" AND EXTRACT(MONTH FROM d) = 10 AND EXTRACT(DAY FROM d) = 10 OR
  d BETWEEN "2000-01-01" AND "2019-12-31" AND EXTRACT(MONTH FROM d) = 10 AND EXTRACT(DAYOFWEEK FROM d) =
  2 AND EXTRACT(DAY FROM d) BETWEEN 8 AND 14
);
