-- 敬老の日	九月の第三月曜日
config {
  type: "operations",
  hasOutput: true,
  schema: "holidays_in_japan__asia_northeast1"
}
CREATE OR REPLACE FUNCTION ${self()}(d DATE)
AS (
  d BETWEEN "1966-01-01" AND "2002-12-31" AND EXTRACT(MONTH FROM d) = 9 AND EXTRACT(DAY FROM d) = 15 OR
  "2003-01-01" <= d AND EXTRACT(MONTH FROM d) = 9 AND EXTRACT(DAYOFWEEK FROM d) = 2 AND EXTRACT(DAY FROM d) BETWEEN 15 AND
  21
);
