-- 敬老の日	九月の第三月曜日
CREATE OR REPLACE FUNCTION holidays_in_japan.IS_RESPECT_FOR_THE_AGED_DAY(d DATE)
AS (
  d BETWEEN "1966-01-01" AND "2002-12-31" AND EXTRACT(MONTH FROM d) = 9 AND EXTRACT(DAY FROM d) = 15 OR
  "2003-01-01" <= d AND EXTRACT(MONTH FROM d) = 9 AND EXTRACT(DAYOFWEEK FROM d) = 2 AND EXTRACT(DAY FROM d) BETWEEN 15 AND
  21
);
