CREATE OR REPLACE FUNCTION holidays_in_japan.NETWORKDAYS_ON_OFF_WEEKEND_DAYS_AND_HOLIDAYS_IN_JAPAN(start_date DATE, end_date DATE)
AS (
  (
    SELECT
      COUNTIF(holidays_in_japan.HOLIDAY_NAME(d) IS NULL AND EXTRACT(DAYOFWEEK FROM d) NOT IN (1, 7))
    FROM
      UNNEST(GENERATE_DATE_ARRAY(start_date, end_date)) AS d
  )
);
